### ISSUE TITLE
Update NodejS version from `node16` to `node20`

### ISSUE THREAD

**Issue by giordano** [julia-actions/cache#109]
Node 16 is deprecated
https://github.com/julia-actions/cache/blob/b1b004ffca7da8ece08fe42c9ee0ec4fc2cc5ca5/action.yml#L118
https://github.com/julia-actions/cache/blob/b1b004ffca7da8ece08fe42c9ee0ec4fc2cc5ca5/action.yml#L139
https://github.com/julia-actions/cache/blob/b1b004ffca7da8ece08fe42c9ee0ec4fc2cc5ca5/action.yml#L150
https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

**Comment by giordano** [comment]
#107 probably addresses the issue for `actions/cache`, but `pyTooling/Actions/with-post-step` seems to be stuck to node16 upstream.

**Comment by DilumAluthge** [comment]
Here's the issue I opened upstream for a new release of `pyTooling/Actions` that includes the `node20` bump: https://github.com/pyTooling/Actions/issues/77

**Comment by DilumAluthge** [comment]
This issue will be fixed by the combination of https://github.com/julia-actions/cache/pull/123 and https://github.com/julia-actions/cache/pull/125.

**Comment by DilumAluthge** [comment]
#123 and #127 have been merged.

**Comment by DilumAluthge** [comment]
This issue has been fixed by the combination of https://github.com/julia-actions/cache/pull/123, https://github.com/julia-actions/cache/pull/127, and https://github.com/julia-actions/cache/releases/tag/v2.0.0.

I've already created the `v2.0.0` tag. I'll create the `v2` tag shortly.

**Comment by DilumAluthge** [comment]
I've created the `v2` tag.
