### ISSUE TITLE
Assumes Julia is installed

### ISSUE THREAD

**Issue by IanButterworth** [julia-actions/cache#142]
The registry update step assumes julia is installed and fails the job if it's not. 

cc. @giordano

**Comment by IanButterworth** [comment]
Weirdly it seems that macOS GitHub runners don't seem to have julia pre-installed but others do, as expected. 

But either way we shouldn't fail because self hosted runners might not also.

**Comment by giordano** [comment]
Example: https://github.com/JuliaMath/QuadGK.jl/actions/runs/10640418662/job/29500338448
```
Registries directory exists and is non-empty. Updating any registries
/Users/runner/work/_temp/76e2caee-c42d-4eab-a2b1-ac350daddc95.sh: line 3: julia: command not found
Error: Process completed with exit code 127.
```
