### ISSUE TITLE
Julia's version is not taken into account

### ISSUE THREAD

**Issue by rikhuijzer** [julia-actions/cache#46]
Julia's version is currently not taken into account in the cache key. This probably has a negative effect on the usefulness of the compiled cache when there are multiple Julia versions being cached.

Is this something we can fix? Would it be safe for us to read out `julia -e 'println(VERSION)'`?

**Comment by giordano** [comment]
The compile cache is already indexed by the julia version on the file system, no?

**Comment by rikhuijzer** [comment]
Yes, but that could still mean that a cache by Julia version X results in a lot of X-specific files which are useless when restored on Julia version Y.

**Comment by SaschaMann** [comment]
We could add `julia --version` to the cache key if that's useful. Particularly with #45 that moves the compiled cache to a separate cache anyway.
