### ISSUE TITLE
Replace commas in cache key to make actions/cache happy

### ISSUE THREAD

**Issue by iamed2** [julia-actions/cache#92]
Now that matrix vars are included, it's more likely you'll run into commas in the cache key and get this error (assume `[...]` is a key with a comma):

```
Error: Key Validation Error: [...] cannot contain commas.
```

This restriction is [not documented](https://github.com/actions/cache/issues/1225) by GitHub but is checked here: https://github.com/actions/toolkit/blob/5430c5d84832076372990c7c27f900878ff66dc9/packages/cache/src/cache.ts#L32-L44

Ran into this in a private package using comma-separated lists in a value in the matrix.

**Comment by IanButterworth** [comment]
@omus do you see a simple fix?

**Comment by omus** [comment]
Fixed by: https://github.com/julia-actions/cache/pull/93
