### ISSUE TITLE
error when using cache action after `add-julia-registry` 

### ISSUE THREAD

**Issue by kleinschmidt** [julia-actions/cache#94]
This has happened on two Beacon repos where we use `add-julia-registry` to add our private registry.  If `julia-actions/cache` is run _after_ that, then on `Pkg.test` we get errors like this:

```
  Activating new project at `~/.julia/environments/tests-logger-env`
    Updating registry at `~/.julia/registries/Beacon`
    Updating git-repo `[registry URI]`
ERROR: LoadError: GitError(Code:EMERGECONFLICT, Class:Checkout, 4 conflicts prevent checkout)
```

that goes away when we remove the cache action, and it goes away if we run the cache action _before_ `add-julia-registry`.

**Comment by omus** [comment]
Here is my theory on what is happening:

When `add-julia-registry` is used before `julia-actions/cache` the former action creates Git clones of a private registry and the General registry. When the Julia cache action runs, with registry caching enabled, a simple tarball extraction occurs which would modify the worktree of the registry clone. Once the `Pkg.Registry.update` via `Pkg.instantiate` through `julia-actions/julia-runtest` the dirty worktree results in conflicts when trying to update the registry.

The reason this issue just started occurring recently is that registry caching is now on by default. This can be fixed having the cache step occur before `add-julia-registry` or using the option `cache-registries: false` with the Julia cache action (not recommended).

One option to transparency fix this would be to automatically exclude the registry directory from the cache when we detect existing content in the registry dir. Unfortunately, this would also result in the registry from not being saved at the end of the run which could lead to other issues later when reordering the actions.

**Comment by omus** [comment]
I validated my theory in #102 and implemented the transparent fix for this.
